apimServiceName: apim-cicd-qa-hv
namedValues:
  - name: func-cicd-qa-hv-key
    properties:
      displayName: func-cicd-qa-hv-key
      value: "l2uVL02bNVAPP6ZJOQW2XU4ZluNkrfhUYtwoBQPfdNxHtHmcl5HREQ=="
loggers:
diagnostics:
backends:
  - name: func-cicd-qa-hv
    properties:
      url: "https://func-cicd-qa-hv.azurewebsites.net/api"
      resourceId: "https://management.azure.com/subscriptions/92449014-82af-46f5-9261-e493e2c046fc/resourceGroups/rgp-davies/providers/Microsoft.Web/sites/func-cicd-qa-hv"
apis: