apimServiceName: apim-cicd-qa-hv
namedValues:
  - name: func-cicd-hv-key
    properties:
      displayName: func-cicd-hv
      value: "HisORF8MmsmWC4xtr6vSIYBWdlMmvFA5Dv4px8WuI4-mAzFurhel9Q=="
loggers:
diagnostics:
backends:
  - name: func-cicd-hv
    properties:
      url: "https://func-cicd-qa-hv.azurewebsites.net/api"
      resourceId: "https://management.azure.com/subscriptions/92449014-82af-46f5-9261-e493e2c046fc/resourceGroups/rgp-davies/providers/Microsoft.Web/sites/func-cicd-qa-hv"
apis: