openapi: 3.0.1
info:
  title: 'Hoang '
  description: This is the OpenAPI Document on Azure Functions
  version: '1.0'
servers:
  - url: https://apim-cicd-dev-hv.azure-api.net/hoanglun
paths:
  /Data:
    get:
      summary: getMyData
      description: getMyData
      operationId: getMyData
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                type: string
              example: string
    put:
      summary: Modify data
      description: UPDATE data.
      operationId: modify-data
      responses:
        '200':
          description: ''
    delete:
      summary: Remove data
      description: DELETE data.
      operationId: remove-data
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]