swagger: '2.0'
info:
  title: OpenAPI Document on Azure Functions
  description: This is the OpenAPI Document on Azure Functions
  version: 1.0.0
host: 'localhost:7018'
basePath: /api
schemes:
  - http
paths:
  /GetMyData:
    get:
      tags:
        - data
      operationId: getMyData
      produces:
        - application/json
      responses:
        '200':
          description: Successful
          schema:
            type: string
