openapi: 3.0.1
info:
  title: 'Hoang '
  description: This is the OpenAPI Document on Azure Functions
  version: '1.0'
servers:
  - url: https://apim-cicd-dev-hv.azure-api.net/demo
paths:
  /GetMyData:
    get:
      tags:
        - data
      summary: getMyData
      description: getMyData
      operationId: getMyData
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                type: string
              example: string
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]