openapi: 3.0.1
info:
  title: Demo2
  description: This is the OpenAPI Document on Azure Functions
  version: '1.0'
servers:
  - url: https://apim-cicd-dev-hv.azure-api.net/demo2
paths: { }
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]